
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: fb-deploy
  labels:
    app: fb-app
    env: prod
spec:
  replicas: 3
 
  selector:
    matchLabels:
      app: fb-app
      env: prod
  template:
    metadata: 
      labels:
        app: fb-app
        env: prod
        version: v2_vc

    spec:
      containers: 
      - name: facebook-container
        image: vineethsankre/vineethapp:18
        ports:
        - containerPort: 8080
